[package]
name = "web"
version = "0.1.0"
authors = ["Lyndon Maydwell <lyndon@sordina.net>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
# pikelet = { git = "https://github.com/pikelet-lang/pikelet" }
